---
title: "$f(\\alpha\\zeta)$"
---

$$
y = \sin(\alpha \zeta) \qquad \alpha \in \{0,0.1,0.2,...,3\}
$$


```{r, cache = T, echo = F, fig.align='center', message = F, warning = F}
library(tidyverse)

cool_function   <- function(x, alpha) return(sin(alpha*x))
xs              <- seq(0, pi*1.5, 0.005)
ys              <- cool_function(xs, 1)
results         <- tibble(xs, ys, alpha = "1")

for(alpha in seq(0, 3, 0.1)){
  results <- results %>% 
    bind_rows(data_frame(xs, 
                         ys = cool_function(xs, alpha),
                         alpha = as.character(alpha)))
}

ggplot(results, aes(x = xs, y = ys, color = alpha)) + 
  geom_line() + 
  theme_bw() + 
  theme(legend.position = "none") +
    theme(axis.text.x = element_blank(),   # remove x axis labels
          axis.ticks.x = element_blank(),  # remove x axis ticks
          axis.text.y = element_blank(),   # remove y axis labels
          axis.ticks.y = element_blank())  # remove y axis ticks
```



# Weierstrass Function

$$
f(x) = \sum_{n=0}^{\infty} a^n \cdot \cos(b^n \pi x)
$$

Where $a \in (0,1)$, $b$ is a positive, odd integer, and $ab > 1+\frac{3}{2}\pi$. The minimum value of $b$ for which these constraints are satisfied is $b=7$.

```{r, cache = T, echo = F, fig.align='center', message = F, warning = F}
fx <- function(x, a = 0.75, b = 5, max = 100) {
    sum( a^(1:max) * cos(b^(1:max) * pi * x) )
}

x <- seq(-1, 1, 0.005)
y <- lapply(x, FUN = fx)

plot(x, y, type = "l")
```


```{r}
# library(tidyverse)
# cool_function   <- function(x, a = 0.75, b = 5, max = 100) {
#     sum( a^(1:max) * cos(b^(1:max) * pi * x) )
# }
# xs              <- seq(-1, 1, 0.001)
# ys              <- cool_function(xs)
# results         <- tibble(xs, ys, a = "1")
# 
# for(alpha in seq(0.001, .999, 0.001)){
#   results <- results %>% 
#     bind_rows(data_frame(xs, 
#                          ys = cool_function(xs, alpha),
#                          alpha = as.character(alpha)))
# }
# 
# ggplot(results, aes(x = xs, y = ys, color = alpha)) + 
#   geom_line() + 
#   theme_bw() + 
#   theme(legend.position = "none") +
#     theme(axis.text.x = element_blank(),   # remove x axis labels
#           axis.ticks.x = element_blank(),  # remove x axis ticks
#           axis.text.y = element_blank(),   # remove y axis labels
#           axis.ticks.y = element_blank())  # remove y axis ticks
```




